name: 'Container Images Sync Tools'
description: 'Container Images Sync Tools'
author: 'admin <admin@china.cn>'
inputs:
  GIT_TOKEN:
    description: 'github token'
    default: ''
  GIT_ORG:
    description: 'github org'
    default: 'cn-xyz'
  GIT_REPO:
    description: 'github repo'
    default: 'image-sync'
  SRC_IMAGE_LIST_URL:
    description: 'SRC_IMAGE_LIST_URL'
    default: 'https://raw.githubusercontent.com/cn-xyz/image-sync/main/k8s.txt'
  DEST_REPO:
    description: 'DEST register REPO'
    default: 'docker.io/cnxyz'
  SRC_TRANSPORT:
    description: 'SRC TRANSPORT'
    default: 'docker'
  DEST_TRANSPORT:
    description: 'DEST TRANSPORT'
    default: 'docker'
  THREAD_POOL_NUM:
    description: 'sync thread pool num'
    default: 2
  LOG_LEVEL:
    description: 'logger level, value [DEBUG|INFO|WARN|ERROR|FATAL]'
    default: 'DEBUG'
runs:
  using: 'docker'
  image: 'Dockerfile'

branding:
  color: 'blue'
  icon: 'repeat'
